baseURL = "https://www.mariaisabelballester.com/"
languageCode = "es-es"
title = "María Isabel Ballester - Escultura"
theme = "hugo-creative-portfolio-theme"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "blue"
  description = "María Isabel Ballester. Esculturas."
  copyright = "&copy;2017 María Isabel Ballester"
  sidebarAbout = [
    "Escultora, artista. Estudia dos años en la escuela de artes y oficios de Palma, donde desarrolla su obra y también da clases de escultura.",
    "Nace en Buenos Aires en 1960. Desde 1979 vive en Palma de Mallorca (Baleares), donde descubre y desarrolla su actividad artística."
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "mibesculturas@gmail.com"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Portfolio"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "Exhibitions"
  url = "exhibitions/"

  [[params.navlinks]]
  name = "Outstanding Works"
  url = "outstanding/"

  [params.social]
  facebook      = "https://www.facebook.com/esculturasisabelballester"
  email         = "mibesculturas@gmail.com"
  instagram     = "https://www.instagram.com/mibesculturas/"